# Generated by Django 4.2.7 on 2023-11-11 16:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(200)]),
        ),
    ]
