# Generated by Django 5.1.5 on 2025-01-22 21:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_remove_user_email_remove_user_email_verified_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_moderator",
        ),
    ]
