# Generated by Django 5.1.5 on 2025-01-26 18:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_remove_user_is_moderator"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="bio",
        ),
    ]
