# Generated by Django 5.1.5 on 2025-01-29 20:11

from django.db import migrations, models

import users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_remove_user_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to=users.models.avatar_upload_destination),
        ),
    ]
