# Generated by Django 5.2 on 2025-12-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="aliases",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Alternative names for this entity (e.g., translations, original titles)",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="aliases",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Alternative names for this entity (e.g., translations, original titles)",
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="aliases",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Alternative names for this entity (e.g., translations, original titles)",
            ),
        ),
        migrations.AddField(
            model_name="show",
            name="aliases",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Alternative names for this entity (e.g., translations, original titles)",
            ),
        ),
    ]
