# Generated by Django 4.2.6 on 2023-10-20 16:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0003_unique_name_constraints"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="author",
        ),
        migrations.RemoveField(
            model_name="game",
            name="producer",
        ),
        migrations.RemoveField(
            model_name="game",
            name="publisher",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="cast",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="director",
        ),
        migrations.RemoveField(
            model_name="show",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="show",
            name="stars",
        ),
        migrations.DeleteModel(
            name="Identity",
        ),
        migrations.AddField(
            model_name="book",
            name="author",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), blank=True, default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="producer",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), blank=True, default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="publisher",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), blank=True, default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="cast",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), blank=True, default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="director",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), blank=True, default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="show",
            name="creator",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), blank=True, default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="show",
            name="stars",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), blank=True, default=list, size=None
            ),
        ),
    ]
