# Generated by Django 4.2.6 on 2023-10-30 21:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0004_remove_book_author_remove_game_producer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="goodreads_url",
            field=models.URLField(blank=True, verbose_name="Goodreads URL"),
        ),
        migrations.AddField(
            model_name="game",
            name="steam_url",
            field=models.URLField(blank=True, verbose_name="Steam URL"),
        ),
        migrations.AddField(
            model_name="movie",
            name="imdb_url",
            field=models.URLField(blank=True, verbose_name="IMDB URL"),
        ),
        migrations.AddField(
            model_name="show",
            name="imdb_url",
            field=models.URLField(blank=True, verbose_name="IMDB URL"),
        ),
        migrations.AlterField(
            model_name="book",
            name="description",
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(500)]),
        ),
        migrations.AlterField(
            model_name="book",
            name="wikipedia_url",
            field=models.URLField(blank=True, verbose_name="Wikipedia URL"),
        ),
        migrations.AlterField(
            model_name="game",
            name="description",
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(500)]),
        ),
        migrations.AlterField(
            model_name="game",
            name="wikipedia_url",
            field=models.URLField(blank=True, verbose_name="Wikipedia URL"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="description",
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(500)]),
        ),
        migrations.AlterField(
            model_name="movie",
            name="wikipedia_url",
            field=models.URLField(blank=True, verbose_name="Wikipedia URL"),
        ),
        migrations.AlterField(
            model_name="show",
            name="description",
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(500)]),
        ),
        migrations.AlterField(
            model_name="show",
            name="wikipedia_url",
            field=models.URLField(blank=True, verbose_name="Wikipedia URL"),
        ),
    ]
