# Generated by Django 4.2.7 on 2023-11-11 16:38

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0006_rename_producer_game_developer"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="book",
            name="book_unique_name",
        ),
        migrations.RemoveConstraint(
            model_name="game",
            name="game_unique_name",
        ),
        migrations.RemoveConstraint(
            model_name="movie",
            name="movie_unique_name",
        ),
        migrations.RemoveConstraint(
            model_name="show",
            name="show_unique_name",
        ),
        migrations.AddConstraint(
            model_name="book",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="book_unique_name",
                violation_error_message="Item with that name already exists.",
            ),
        ),
        migrations.AddConstraint(
            model_name="game",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="game_unique_name",
                violation_error_message="Item with that name already exists.",
            ),
        ),
        migrations.AddConstraint(
            model_name="movie",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="movie_unique_name",
                violation_error_message="Item with that name already exists.",
            ),
        ),
        migrations.AddConstraint(
            model_name="show",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="show_unique_name",
                violation_error_message="Item with that name already exists.",
            ),
        ),
    ]
