# Generated by Django 4.2.7 on 2023-11-12 18:27

from pathlib import Path

from django.core.files.storage import default_storage
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps

from entities.models import image_upload_destination


def migrate_image_filenames(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    Movie = apps.get_model("entities", "Movie")
    Show = apps.get_model("entities", "Show")
    Book = apps.get_model("entities", "Book")
    Game = apps.get_model("entities", "Game")

    for Model in (Movie, Show, Book, Game):
        for instance in Model.objects.exclude(image=""):
            old_file_path = instance.image.name
            new_file_path = image_upload_destination(instance, Path(old_file_path).name)

            # If the file exists on S3
            if default_storage.exists(old_file_path):
                # Copy the file to the new path
                file_content = default_storage.open(old_file_path)
                default_storage.save(new_file_path, file_content)

                # Delete the old file
                default_storage.delete(old_file_path)

                # Update the record in the database
                instance.image.name = new_file_path
                instance.save(update_fields=["image"])


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0007_remove_book_book_unique_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="image",
            field=models.ImageField(blank=True, default="", upload_to=image_upload_destination),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="game",
            name="image",
            field=models.ImageField(blank=True, default="", upload_to=image_upload_destination),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="movie",
            name="image",
            field=models.ImageField(blank=True, default="", upload_to=image_upload_destination),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="show",
            name="image",
            field=models.ImageField(blank=True, default="", upload_to=image_upload_destination),
            preserve_default=False,
        ),
        migrations.RunPython(migrate_image_filenames, migrations.RunPython.noop),
    ]
