# Generated by Django 4.2.7 on 2024-01-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0008_change_uploaded_filenames"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="name",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="game",
            name="name",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="movie",
            name="name",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="show",
            name="name",
            field=models.CharField(max_length=128),
        ),
    ]
