# Generated by Django 5.1.5 on 2025-01-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0011_remove_book_approved_remove_book_draft_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Platform",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.RemoveField(
            model_name="game",
            name="platforms",
        ),
        migrations.AddField(
            model_name="game",
            name="platforms",
            field=models.ManyToManyField(blank=True, to="entities.platform"),
        ),
    ]
