# Generated by Django 5.1.5 on 2025-01-26 18:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0012_platform_remove_game_platforms_game_platforms"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="game",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="show",
            name="created_by",
        ),
    ]
