# Generated by Django 5.1.5 on 2025-01-26 22:15

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0013_remove_book_created_by_remove_game_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="search_vector",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.contrib.postgres.search.SearchVector("name", config="english"),
                output_field=django.contrib.postgres.search.SearchVectorField(),
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="search_vector",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.contrib.postgres.search.SearchVector("name", config="english"),
                output_field=django.contrib.postgres.search.SearchVectorField(),
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="search_vector",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.contrib.postgres.search.SearchVector("name", config="english"),
                output_field=django.contrib.postgres.search.SearchVectorField(),
            ),
        ),
        migrations.AddField(
            model_name="show",
            name="search_vector",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.contrib.postgres.search.SearchVector("name", config="english"),
                output_field=django.contrib.postgres.search.SearchVectorField(),
            ),
        ),
        migrations.AddIndex(
            model_name="book",
            index=django.contrib.postgres.indexes.GinIndex(fields=["search_vector"], name="book_gin_search_vector_idx"),
        ),
        migrations.AddIndex(
            model_name="game",
            index=django.contrib.postgres.indexes.GinIndex(fields=["search_vector"], name="game_gin_search_vector_idx"),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="movie_gin_search_vector_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="show",
            index=django.contrib.postgres.indexes.GinIndex(fields=["search_vector"], name="show_gin_search_vector_idx"),
        ),
    ]
