# Generated by Django 5.1.5 on 2025-02-11 20:41

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0014_book_search_vector_game_search_vector_and_more"),
    ]

    operations = [
        TrigramExtension(),
        migrations.RemoveIndex(
            model_name="book",
            name="book_gin_search_vector_idx",
        ),
        migrations.RemoveIndex(
            model_name="game",
            name="game_gin_search_vector_idx",
        ),
        migrations.RemoveIndex(
            model_name="movie",
            name="movie_gin_search_vector_idx",
        ),
        migrations.RemoveIndex(
            model_name="show",
            name="show_gin_search_vector_idx",
        ),
        migrations.RemoveField(
            model_name="book",
            name="search_vector",
        ),
        migrations.RemoveField(
            model_name="game",
            name="search_vector",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="search_vector",
        ),
        migrations.RemoveField(
            model_name="show",
            name="search_vector",
        ),
        migrations.AddIndex(
            model_name="book",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"], name="book_trgm_name_idx", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"], name="game_trgm_name_idx", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"], name="movie_trgm_name_idx", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="show",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"], name="show_trgm_name_idx", opclasses=["gin_trgm_ops"]
            ),
        ),
    ]
