# Generated by Django 5.1.5 on 2025-03-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0015_remove_book_book_gin_search_vector_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookTag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "ordering": ("name",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GameTag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "ordering": ("name",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MovieTag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "ordering": ("name",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShowTag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "ordering": ("name",),
                "abstract": False,
            },
        ),
        migrations.RenameModel(
            old_name="Tag",
            new_name="GenericTag",
        ),
        migrations.AddField(
            model_name="book",
            name="new_tags",
            field=models.ManyToManyField(blank=True, to="entities.booktag"),
        ),
        migrations.AddField(
            model_name="game",
            name="new_tags",
            field=models.ManyToManyField(blank=True, to="entities.gametag"),
        ),
        migrations.AddField(
            model_name="movie",
            name="new_tags",
            field=models.ManyToManyField(blank=True, to="entities.movietag"),
        ),
        migrations.AddField(
            model_name="show",
            name="new_tags",
            field=models.ManyToManyField(blank=True, to="entities.showtag"),
        ),
    ]
