# Generated by Django 5.1.5 on 2025-03-06 22:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0016_booktag_gametag_movietag_showtag_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GenericTag",
        ),
        migrations.RemoveField(
            model_name="book",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="game",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="show",
            name="tags",
        ),
        migrations.RenameField(
            model_name="book",
            old_name="new_tags",
            new_name="tags",
        ),
        migrations.RenameField(
            model_name="game",
            old_name="new_tags",
            new_name="tags",
        ),
        migrations.RenameField(
            model_name="movie",
            old_name="new_tags",
            new_name="tags",
        ),
        migrations.RenameField(
            model_name="show",
            old_name="new_tags",
            new_name="tags",
        ),
    ]
