# Generated by Django 5.1.5 on 2025-03-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0017_delete_generictag_remove_book_new_tags_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="slug",
            field=models.SlugField(max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="game",
            name="slug",
            field=models.SlugField(max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="slug",
            field=models.SlugField(max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="show",
            name="slug",
            field=models.SlugField(max_length=128, null=True, unique=True),
        ),
    ]
