# Generated by Django 5.1.5 on 2025-03-08 06:50

import random
import string
from io import BytesIO
from pathlib import Path

from django.core.files import File
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps
from django.utils.text import slugify

from entities.models import image_upload_destination


def add_slugs_and_migrate_image_filenames(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    Movie = apps.get_model("entities", "Movie")
    Show = apps.get_model("entities", "Show")
    Book = apps.get_model("entities", "Book")
    Game = apps.get_model("entities", "Game")

    for Model in (Movie, Show, Book, Game):
        for instance in Model.objects.filter(slug__isnull=True):
            instance.slug = slugify(instance.name)

            old_file_path = instance.image.name
            new_file_path = image_upload_destination(instance, Path(old_file_path).name)

            if instance.image:
                try:
                    image_buffer = File(BytesIO(instance.image.read()))
                    instance.image.delete(save=False)
                    instance.image.save(new_file_path, image_buffer, save=False)
                except Exception:
                    instance.image.delete(save=False)

            try:
                instance.save(update_fields=["slug", "image"])
            except Exception:
                instance.slug = instance.slug + "".join(random.choices(string.ascii_letters + string.digits, k=2))  # noqa: S311
                instance.save(update_fields=["slug", "image"])


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("entities", "0018_book_slug_game_slug_movie_slug_show_slug"),
    ]

    operations = [
        migrations.RunPython(add_slugs_and_migrate_image_filenames, reverse_code=migrations.RunPython.noop),
    ]
