# Generated by Django 5.1.5 on 2025-03-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0019_add_slugs_to_all_entities"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="slug",
            field=models.SlugField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="slug",
            field=models.SlugField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="slug",
            field=models.SlugField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name="show",
            name="slug",
            field=models.SlugField(max_length=128, unique=True),
        ),
    ]
