# Generated by Django 5.2 on 2025-04-27 17:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0021_booktag_aliases_gametag_aliases_movietag_aliases_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="platform",
            name="aliases",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), blank=True, default=list, size=None
            ),
        ),
    ]
