# Generated by Django 5.2 on 2025-09-29 09:32

from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps


def migrate_array_field_to_json_field(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    Book = apps.get_model("entities", "Book")
    BookTag = apps.get_model("entities", "BookTag")

    for book in Book.objects.all():
        book.json_author = book.author
        book.save(update_fields=["json_author"])

    for book_tag in BookTag.objects.all():
        book_tag.json_aliases = book_tag.aliases
        book_tag.save(update_fields=["json_aliases"])

    Game = apps.get_model("entities", "Game")
    GameTag = apps.get_model("entities", "GameTag")

    for game in Game.objects.all():
        game.json_developer = game.developer
        game.json_publisher = game.publisher
        game.save(update_fields=["json_developer", "json_publisher"])

    for game_tag in GameTag.objects.all():
        game_tag.json_aliases = game_tag.aliases
        game_tag.save(update_fields=["json_aliases"])

    Movie = apps.get_model("entities", "Movie")
    MovieTag = apps.get_model("entities", "MovieTag")

    for movie in Movie.objects.all():
        movie.json_director = movie.director
        movie.json_cast = movie.cast
        movie.save(update_fields=["json_director", "json_cast"])

    for movie_tag in MovieTag.objects.all():
        movie_tag.json_aliases = movie_tag.aliases
        movie_tag.save(update_fields=["json_aliases"])

    Show = apps.get_model("entities", "Show")
    ShowTag = apps.get_model("entities", "ShowTag")

    for show in Show.objects.all():
        show.json_creator = show.creator
        show.json_stars = show.stars
        show.save(update_fields=["json_creator", "json_stars"])

    for show_tag in ShowTag.objects.all():
        show_tag.json_aliases = show_tag.aliases
        show_tag.save(update_fields=["json_aliases"])

    Platform = apps.get_model("entities", "Platform")

    for platform in Platform.objects.all():
        platform.json_aliases = platform.aliases
        platform.save(update_fields=["json_aliases"])


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0022_platform_aliases"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="json_author",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="booktag",
            name="json_aliases",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="game",
            name="json_developer",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="game",
            name="json_publisher",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="gametag",
            name="json_aliases",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="movie",
            name="json_cast",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="movie",
            name="json_director",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="movietag",
            name="json_aliases",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="platform",
            name="json_aliases",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="show",
            name="json_creator",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="show",
            name="json_stars",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="showtag",
            name="json_aliases",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(migrate_array_field_to_json_field, migrations.RunPython.noop),
    ]
