# Generated by Django 5.2 on 2025-09-29 09:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0023_book_json_author_booktag_json_aliases_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="author",
        ),
        migrations.RemoveField(
            model_name="booktag",
            name="aliases",
        ),
        migrations.RemoveField(
            model_name="game",
            name="developer",
        ),
        migrations.RemoveField(
            model_name="game",
            name="publisher",
        ),
        migrations.RemoveField(
            model_name="gametag",
            name="aliases",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="cast",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="director",
        ),
        migrations.RemoveField(
            model_name="movietag",
            name="aliases",
        ),
        migrations.RemoveField(
            model_name="platform",
            name="aliases",
        ),
        migrations.RemoveField(
            model_name="show",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="show",
            name="stars",
        ),
        migrations.RemoveField(
            model_name="showtag",
            name="aliases",
        ),
    ]
