# Generated by Django 5.2 on 2025-09-29 09:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0024_remove_book_author_remove_booktag_aliases_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="json_author",
            new_name="author",
        ),
        migrations.RenameField(
            model_name="booktag",
            old_name="json_aliases",
            new_name="aliases",
        ),
        migrations.RenameField(
            model_name="game",
            old_name="json_developer",
            new_name="developer",
        ),
        migrations.RenameField(
            model_name="game",
            old_name="json_publisher",
            new_name="publisher",
        ),
        migrations.RenameField(
            model_name="gametag",
            old_name="json_aliases",
            new_name="aliases",
        ),
        migrations.RenameField(
            model_name="movie",
            old_name="json_cast",
            new_name="cast",
        ),
        migrations.RenameField(
            model_name="movie",
            old_name="json_director",
            new_name="director",
        ),
        migrations.RenameField(
            model_name="movietag",
            old_name="json_aliases",
            new_name="aliases",
        ),
        migrations.RenameField(
            model_name="platform",
            old_name="json_aliases",
            new_name="aliases",
        ),
        migrations.RenameField(
            model_name="show",
            old_name="json_creator",
            new_name="creator",
        ),
        migrations.RenameField(
            model_name="show",
            old_name="json_stars",
            new_name="stars",
        ),
        migrations.RenameField(
            model_name="showtag",
            old_name="json_aliases",
            new_name="aliases",
        ),
    ]
