# Generated by Django 5.2 on 2025-09-29 11:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0025_rename_json_author_book_author_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="book",
            name="book_trgm_name_idx",
        ),
        migrations.RemoveIndex(
            model_name="game",
            name="game_trgm_name_idx",
        ),
        migrations.RemoveIndex(
            model_name="movie",
            name="movie_trgm_name_idx",
        ),
        migrations.RemoveIndex(
            model_name="show",
            name="show_trgm_name_idx",
        ),
    ]
