# Generated by Django 4.2.3 on 2023-08-21 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackingObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("object_id", models.PositiveIntegerField()),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Planned"),
                            (1, "In Progress"),
                            (2, "Completed"),
                            (3, "Dropped"),
                            (4, "On Hold"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["object_id", "content_type"],
                        name="tracking_tr_object__10fa5f_idx",
                    ),
                    models.Index(fields=["user", "status"], name="tracking_tr_user_id_f4aaa7_idx"),
                ],
            },
        ),
    ]
