# Generated by Django 4.2.7 on 2023-11-11 16:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tracking", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userstats",
            options={"verbose_name": "User Stats", "verbose_name_plural": "User Stats"},
        ),
    ]
