# Generated by Django 4.2.7 on 2023-11-12 21:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tracking", "0003_alter_userstats_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserStats",
        ),
    ]
